Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 100

Style/ClassAndModuleChildren:
  Enabled: false

Layout/EmptyLinesAroundModuleBody:
  Enabled: false

Style/CommentAnnotation:
  Enabled: false

Layout/EmptyLinesAroundClassBody:
  Enabled: false

Security/Eval:
  Enabled: false

Layout/EmptyLinesAroundBlockBody:
  Enabled: false
